name: Build and Deploy
on:
  push:
    branches: [master]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 1

      - name: Download pandoc
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
            repo: jgm/pandoc
            version: tags/2.19.2
            file: pandoc-2.19.2-1-amd64.deb
            target: pandoc-2.19.2-1-amd64.deb

      - name: Install and Build
        run: |
            sudo dpkg -i pandoc-2.19.2-1-amd64.deb
            pandoc --version
            make

      - name: Checkout liballeg
        uses: actions/checkout@v4
        with:
          repository: liballeg/liballeg.github.io
          ssh-key: ${{ secrets.LIBALLEG_DEPLOY_KEY }}
          ref: master
          path: liballeg

      - name: Deploy
        run: |
          cd liballeg
          git config user.name "allebot"
          git config user.email "13711631+allebot@users.noreply.github.com"
          find . -type f ! \( -path "./.git/*" -o -path "./CNAME" -o -path "./donations.html" -o -path "./a5docs/4*" -o -path "./a5docs/5*" -o -path "./a5docs/trunk*" -o -path "./docs/docs/*" -o -path "./search/*"  -o -path "./allegro-manual/*" -o -path "./OldFiles/*" -o -path "./files/*"\) -exec rm -f {} +
          cp -R ../OUT/* .
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic update from allegrowww2"
          git push
